let projectList = [
  {
    id: 1,
    coverImg: "/photos/google-play-setup.jpg",
    title: "PROJECT TITLE COMING SOON",
    description:
      "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 2,
    coverImg: "/photos/plasma-control-tech.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 3,
    coverImg: "/photos/beatles-sub.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 4,
    coverImg: "/photos/calexo-display.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 5,
    coverImg: "/photos/dia-del-muerte-prints.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 6,
    coverImg: "/photos/eastman-roofing-wrap.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 7,
    coverImg: "/photos/door-detail.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 8,
    coverImg: "/photos/blm-prints.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 9,
    coverImg: "/photos/got-junk-wall.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 10,
    coverImg: "/photos/john-murray-truck-wrap.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 11,
    coverImg: "/photos/sticker-prints.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 12,
    coverImg: "/photos/sf-city-poster.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 13,
    coverImg: "/photos/google-hello-wall.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 14,
    coverImg: "/photos/sat-night-science.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "",
    images: "",
  },
  {
    id: 15,
    coverImg: "/photos/hagen-dazs.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 16,
    coverImg: "/photos/forest-wall.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
];

export default projectList;
