let projectList = [
  {
    id: 1,
    coverImg: "/project-img/google-play-setup-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description:
      "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 2,
    coverImg: "/project-img/plasma-control-tech-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 3,
    coverImg: "/project-img/beatles-sub-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 4,
    coverImg: "/project-img/calexo-display-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 5,
    coverImg: "/project-img/dia-del-muerte-prints-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 6,
    coverImg: "/project-img/eastman-roofing-wrap-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 7,
    coverImg: "/project-img/door-detail-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
  },
  {
    id: 8,
    coverImg: "/project-img/blm-prints-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 9,
    coverImg: "/project-img/got-junk-wall-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 10,
    coverImg: "/project-img/john-murray-truck-wrap-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 11,
    coverImg: "/project-img/bags-van-3-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 12,
    coverImg: "/project-img/sf-city-poster-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 13,
    coverImg: "/project-img/google-hello-wall-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 14,
    coverImg: "/project-img/sat-night-science-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 15,
    coverImg: "/project-img/hagen-dazs-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
  {
    id: 16,
    coverImg: "/project-img/forest-wall-for-web.jpg",
    title: "PROJECT TITLE COMING SOON",
    description: "Vegan single-origin coffee pug typewriter. Asymmetrical put a bird on it pabst live-edge, bespoke selvage la croix unicorn. Tattooed DIY master cleanse palo santo coloring book pabst waistcoat kombucha chia gentrify YOLO tofu mlkshk polaroid. ",
    images: "",
  },
];

export default projectList;
